apiVersion: v1
kind: Pod
metadata:
  name: nginx-01
  labels:
    podName: nginx-001
    project: example
    appName: example-001
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-02
  labels:
    podName: nginx-002
    project: example
    appName: example-001
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-03
  labels:
    podName: nginx-003
    project: example
    appName: example-002
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-04
  labels:
    podName: nginx-004
    project: example
    appName: example-002
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80